dependencies:
    override:
        - sudo pip install awscli
deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync /home/ubuntu/aw-instaritter-talg-service s3://aw-instaritter-talg-service --delete